### ISSUE TITLE
Show some color on the choropleth to mark regions with NO value

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/liverpool16#10]
* [ ]  Show a specific color on the choropleth to mark regions with NO value - show all polygons even if they don't have data - border/grey
* [ ] empty speech bubbles appear over regions with no data. We should make those regions unselectable. On hover -> "no data". Same for chart

**Comment by aalecs** [comment]
We'll investigate if we can do a pattern fill (hashed or something) and if not we'll fill it with gray

**Comment by danmihaila** [comment]
@aalecs lets try to make the dots smaller to see how it looks. You can post here screenshots and we can ask @yumiendo to check them

**Comment by aalecs** [comment]
@danmihaila & @yumiendo check out these options:

1. Dots & no fill
![screen shot 2016-05-04 at 11 40 51](https://cloud.githubusercontent.com/assets/5638491/15009360/9dc93b7a-11ee-11e6-9ef0-4c4c21421679.png)

2. Dashed & no fill
![screen shot 2016-05-04 at 11 41 31](https://cloud.githubusercontent.com/assets/5638491/15009369/ace4a392-11ee-11e6-82a1-25a0aa2d52b4.png)

3. Dashed & gray fill
![screen shot 2016-05-04 at 11 43 59](https://cloud.githubusercontent.com/assets/5638491/15009377/b79443ce-11ee-11e6-9c89-d8f7614825e9.png)

4. Dashed & no fill
![screen shot 2016-05-04 at 11 44 53](https://cloud.githubusercontent.com/assets/5638491/15009381/be235bda-11ee-11e6-942a-fbc9d585ab69.png)

I personally like option 3, which is currently available with the last commit ;)

**Comment by cjhendrix** [comment]
I prefer 4, then 3. Both are good options cartographically.  Keep in mind that we may also eventually want to overlay national boundaries as well. (#66 )

**Comment by danmihaila** [comment]
I like 4,1,3,2 in this order :) nice job @aalecs

**Comment by aalecs** [comment]
@cjhendrix - Good point with the national boundaries ... then 4 is a better option.
