### ISSUE TITLE
Problem with bottom of the page because of new header taking space

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/liverpool16#105]
@danmihaila @baripembo 
I'm adding a screenshot below to show how the problem looks now on the server:
![screenshot_2016-05-18-01-34-36](https://cloud.githubusercontent.com/assets/6586348/15341747/469a4316-1c99-11e6-8086-acb7c132004e.png)
Notice that the bottom of the chart is not showing well and the logo is missing. 

I had to change a bit the code to implement additional features on the header ( see https://github.com/OCHA-DAP/liverpool16/pull/104/commits/df475ae1f23538a5939e487ce93167fb11480dfa - this will be merged soon ) and now the bottom of the charts section is not pushed out of the viewport anymore:
![screen shot 2016-05-18 at 01 43 49](https://cloud.githubusercontent.com/assets/6586348/15341891/1f31ef58-1c9a-11e6-865b-31f306c7ed72.png)
There is still a problem with the  logo, chart and leaflet text overlapping.

**Comment by baripembo** [comment]
@alexandru-m-g I can take a look at this after your code fix is merged. Right now I am seeing this on iphone 5 which is our smallest targeted device:

<img width="332" alt="screen shot 2016-05-17 at 10 05 30 pm" src="https://cloud.githubusercontent.com/assets/1120835/15345280/a50173f2-1c7b-11e6-9b87-36f0bed57418.png">

**Comment by baripembo** [comment]
Ah I see the issue now when checking on actual device. I will make some adjustments and check in the fix.
