### ISSUE TITLE
Map Explorer: how to reset selection

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#34]
@yumiendo we need to think of a way to reset the selection. Assuming user played a bit with map and charts and filtered but now he/she wants to go back to initial state of selection.
I assume we need a link of button to reset or undo some changes...

**Comment by yumiendo** [comment]
based on https://github.com/OCHA-DAP/liverpool16/issues/57, if all layers gets a box and gets stacked below the dropdown(even if it only appears as chart or map only)

<img width="530" alt="screen shot 2016-05-04 at 5 38 17 pm" src="https://cloud.githubusercontent.com/assets/8006323/15030256/3cc793b8-121f-11e6-82d9-914d95dc3a78.png">

under each layer we can add reset button (and 'reset all layers' at the top)
let me know if there is a situation that cannot be covered by this solution.
