### ISSUE TITLE
Visually integrating the map explorer with HDX

### ISSUE THREAD

**Issue by alexandru-m-g** [OCHA-DAP/liverpool16#4]
The map explorer should look as if it is part of the HDX platform as shown in the design from @yumiendo 
https://drive.google.com/drive/folders/0B2Cgmf3EurKoRk43dVlBVFdMRW8

**Comment by aalecs** [comment]
@yumiendo when we're embedding the map explorer should it have a HDX logo somewhere? 
Also what have you envisioned for sharing the map explorer?

**Comment by danmihaila** [comment]
Desktop view:
- [ ] - use url for map explorer: TBD. Also, implement the way map explorer is receiving which dataset is going to start loading the data.
- [ ] add a link for datasets list
![datasetlist_mapex](https://cloud.githubusercontent.com/assets/3865844/14316062/8efd71ba-fc09-11e5-8729-636eb9fe424d.png)
- [ ] add a link for dataset view page
![datasetpage_mapex](https://cloud.githubusercontent.com/assets/3865844/14316078/a53bc468-fc09-11e5-899b-b1333f89bf29.png)
- [ ] menu item entry?
