### ISSUE TITLE
Map Explorer UI: Chart max values

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#47]
When doing the "decideChartValues" it should take into account only the columns specified in column X and column Y.

**Comment by alexandru-m-g** [comment]
@danmihaila What will be the config property that determines the Y column ?

**Comment by danmihaila** [comment]
>   "charts": [
    {
      "name": "By Date",
      "options": {
        "data": {
          "x": "#date+bin",
          "y": "#affected+sum+displaced",
          "type": "area"
        },

**Comment by danmihaila** [comment]
btw, this is for next sprint :)
