### ISSUE TITLE
How to handle >2 charts?

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#49]
When adding a third chart, it falls off the bottom on the column.  I think the intention is Liverpool was to make the chart panel scrollable.  If we can't tackle that by WHS, we should have some logic for removing a chart when adding a third.

![image](https://cloud.githubusercontent.com/assets/1654485/14881207/536f48fe-0d33-11e6-97f1-1fcd934fede0.png)

**Comment by danmihaila** [comment]
also, the layer is not displayed when selected for FTS! this is a bug

**Comment by yumiendo** [comment]
not sure which solution is easier as MVP
1. make the side panel scrollable (up/down)
2. divide the page height (above fold) and squeeze in 3 charts. (like the screenshot above)

**Comment by danmihaila** [comment]
@aalecs can you please comment?

**Comment by aalecs** [comment]
@yumiendo @danmihaila - I went with option 1 and made the side panel scrollable ... seems better so we won't affect how the charts look

**Comment by danmihaila** [comment]
ok. I will assign it @baripembo to check the mobile part.

**Comment by baripembo** [comment]
this is fixed
