### ISSUE TITLE
Delay in updating visualizations with new data

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#50]
@danmihaila noticed that when a resource is updated (but with the same resource file name), there is a delay of a few minutes before the changes are reflected in the MapExplorer.  This issue is a reminder to discuss with Serban how caching is working.

**Comment by alexandru-m-g** [comment]
I think this is a consequence of the caching on the HXL proxy side. We're using our own instance but I'm not sure if this caching mechanism is embedded in the HXL proxy or it's provided by nginx. Maybe @teodorescuserban knows?

**Comment by teodorescuserban** [comment]
As per your request, I added an additional type to nginx: ```application/json geojson```
As a result, all geojson files will be sent compressed.

For the sample file @danmihaila provided (5620k) the compressed size is 1335k.

Please confirm all is good so I proceed with updating the nginx images and deploy this change in production as well.

Closing. Please feel free to reopen.

pinging @cjhendrix @danmihaila

**Comment by danmihaila** [comment]
@cjhendrix tested. an excellent improvement from 25 secs to 10 secs. We can still work a bit, but this issue can be closed

**Comment by alexandru-m-g** [comment]
@teodorescuserban does this mean that even geojsons served from HDX CKAN will be zipped (not just the ones from the geopreview) ?

**Comment by teodorescuserban** [comment]
aye.
