### ISSUE TITLE
How to handle layers with no map

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#57]
ME currently treats layers with no map (FTS data) as if they did.  We need a different legend entry for these types of layers.

![image](https://cloud.githubusercontent.com/assets/1654485/14951117/eed553c6-1056-11e6-94d0-6da4ab55992e.png)

**Comment by yumiendo** [comment]
Would this work? 
- change "Map layer" to "Data layer" 
- every layer should fall in one of the following categories: Data layer (map/chart), Data layer (chart only)
- also on the dropdown(where you select layers) - for layers with chart only, add "[Chart only]" after the layer title
<img width="379" alt="screen shot 2016-05-04 at 10 04 57 am" src="https://cloud.githubusercontent.com/assets/8006323/15016552/c5c2ef54-11df-11e6-89ad-7cc34f571ac5.png">

Also, the legend for "chart only" data - what kind of legend do we need to account for?
will it always be one color?

**Comment by danmihaila** [comment]
see my last comment on https://github.com/OCHA-DAP/liverpool16/issues/46

**Comment by danmihaila** [comment]
this issue is going to be fixed by this comment https://github.com/OCHA-DAP/liverpool16/issues/46#issuecomment-217138003
