### ISSUE TITLE
Chart disappears when changing to bar graph view

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#59]
I think this is because of a config problem that will be fixed on merge, but just to be sure we don't miss it later:

![image](https://cloud.githubusercontent.com/assets/1654485/14951294/3ca26b4c-1058-11e6-98f5-ec10d004b36b.png)

**Comment by cjhendrix** [comment]
Also, chart doesn't show when switching back to "by date"

**Comment by danmihaila** [comment]
fixed
