### ISSUE TITLE
Chart doesn't render inititally, then renders on zoom in, zoom out

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#61]
On my local instance, after loading the population data

![image](https://cloud.githubusercontent.com/assets/1654485/14958494/54f97acc-108b-11e6-92ab-a781755a32d3.png)

After zooming out and back in one level (`ctrl-`, then `ctrl+`):

![image](https://cloud.githubusercontent.com/assets/1654485/14958527/778efb2a-108b-11e6-826f-db8765932f1e.png)

**Comment by cjhendrix** [comment]
Also seeing it on prod.

**Comment by danmihaila** [comment]
I can not reproduce. I tested from iphone5 live on feature-data. Can u use a clean browser?

**Comment by cjhendrix** [comment]
Correction, I get this behavior consistently on the "test data baseline" layer, which is about to become the WFP market monitor layer (same data, better name)

**Comment by danmihaila** [comment]
Can you write the steps to reproduce?

**Comment by danmihaila** [comment]
this is fixed

**Comment by danmihaila** [comment]
the name of the columns are not good. at resize they are draw
