### ISSUE TITLE
Max function not working when submitted hxl proxy from ME

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#67]
Using the HXL Proxy's "count rows" function works when operation type = sum:
(the negative values are correct)
![image](https://cloud.githubusercontent.com/assets/1654485/14979809/eaf248bc-1124-11e6-9f3f-312f849eee95.png)

But when changing the two `sum` entries below to `max`, the chart is not drawn.  I assume this is because we haven't enabled the max function?  It works in hxl proxy: https://proxy.hxlstandard.org/data/edit?filter01=count&count-tags01=%23country%2Bname&count-spec01=&count-aggregate-tag01=%23meta%2Btest1&url=https%3A%2F%2Fdl.dropboxusercontent.com%2Fu%2F18962396%2Fdumbcopy.csv&sheet=

![image](https://cloud.githubusercontent.com/assets/1654485/14979855/3a8a7426-1125-11e6-8f3a-8f0a0344f087.png)

**Comment by alexandru-m-g** [comment]
max function is implemented now #69
