### ISSUE TITLE
Not easy to notice that there are more layers than what is shown in the dropdown

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#68]
![image](https://cloud.githubusercontent.com/assets/1654485/14986433/32e506a6-114c-11e6-8c49-b42c94b4341f.png)

The scroll bar is not very obvious and users may not see that there are more layers below.

**Comment by danmihaila** [comment]
@aalecs can you please comment here. I know you did something regarding the dropdown...

**Comment by danmihaila** [comment]
found it. duplicated by https://github.com/OCHA-DAP/liverpool16/issues/71
