### ISSUE TITLE
MapExplorer: show all layers in dropdown 

### ISSUE THREAD

**Issue by yumiendo** [OCHA-DAP/liverpool16#71]
<img width="1440" alt="screen shot 2016-05-04 at 2 48 55 pm" src="https://cloud.githubusercontent.com/assets/8006323/15025463/5721cbce-1207-11e6-8376-4a4204fce4ea.png">

can reveal everything in dropdown(and not make it scrollable) since we dont have a lot of layers?

**Comment by danmihaila** [comment]
@yumiendo @baripembo how will look this on mobile?

**Comment by aalecs** [comment]
Fixed

**Comment by baripembo** [comment]
@aalecs I think we need to keep the scrolling functionality for mobile landscape view
