### ISSUE TITLE
Map Explorer: header for mobile

### ISSUE THREAD

**Issue by yumiendo** [OCHA-DAP/liverpool16#73]
As per discussion - we're adding header for mobile but since its a small space, I came up with non-header solution.

at the top of the map explorer screen there is a small banner (once clicking 'x' it will go away) that includes instruction(see below)
![mapex_mob](https://cloud.githubusercontent.com/assets/8006323/15103736/fe74737c-157c-11e6-9394-c695efb6defa.png)

let me know if you have any question -

**Comment by danmihaila** [comment]
@baripembo can you work on this one pls?

**Comment by baripembo** [comment]
@danmihaila yes i can work on this after Homepage responsive

**Comment by baripembo** [comment]
this is done
