### ISSUE TITLE
Y axis doesn't handle negative values very well

### ISSUE THREAD

**Issue by cjhendrix** [OCHA-DAP/liverpool16#78]
The bars look correct, but the ticks and labels on the y axis aren't great.  It would be good to always show the 0 value and some negative number when there are values <0.  Also, this graph would be better if #65 was also solved.

![image](https://cloud.githubusercontent.com/assets/1654485/15149601/7e30aede-16ca-11e6-8e6a-a6243a5c3eb7.png)

**Comment by danmihaila** [comment]
this is done
