### ISSUE TITLE
ME: mobile drop down styles looks bad and can't be full seen

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#88]
I am assigning this to @aalecs as he worked on styling the legend. @baripembo please jump in with any advice if you want.
![screen shot 2016-05-13 at 14 09 18](https://cloud.githubusercontent.com/assets/3865844/15246313/91808e54-1914-11e6-9f46-1bd8028b976a.png)

**Comment by aalecs** [comment]
Fixed yesterday :)

**Comment by danmihaila** [comment]
@aalecs this is not about the dropdown, but the layers that are already selected. As you see in screenshot the "data layer 3" can not be seen.
Pinging @baripembo and @yumiendo for help and assigned to @baripembo . Maybe a scrollbar?

**Comment by danmihaila** [comment]
![screen shot 2016-05-16 at 15 29 59](https://cloud.githubusercontent.com/assets/3865844/15289475/18d4135e-1b7b-11e6-8c81-45655794fbe9.png)
