### ISSUE TITLE
ME : mobile - wrong number of charts

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/liverpool16#89]
I see 4 pages for charts, but there are only 3 added. You can not scroll/click to the last one but it shows 1 extra (4 instead of 3)
![screen shot 2016-05-13 at 14 09 09](https://cloud.githubusercontent.com/assets/3865844/15246332/c27d50b4-1914-11e6-9141-04f7b3216455.png)

**Comment by baripembo** [comment]
I believe this is related to #49 which I am planning to look at today

**Comment by baripembo** [comment]
@danmihaila There are two things going on here:
1) When I select "Estimated Baseline Population" under Displacement category in the layers dropdown, I get errors in the console and no chart is added to the charts panel but the "createChart" function still runs which calls the function that adds a dot to the chart pagination
2) When I select "Some data - month" or "Some data - baseline" in the Test data category, these charts replace each other if one is already present in the charts panel but the "createChart" function still calls the function that adds an additional dot to the chart pagination 

For both of these scenarios, is there a catch or flag I can put in the createChart function that will let me know if either of these scenarios is happening?

**Comment by danmihaila** [comment]
@aalecs please check Erika's comments
